[book]
authors = ["The Rust Project Developers"]
multilingual = false
src = "src"
title = "The Edition Guide"

[output.html]
git-repository-url = "https://github.com/rust-lang/edition-guide"

[output.html.redirect]
"/rust-2018/edition-changes.html" = "/rust-2018/index.html"
"/rust-2018/module-system/index.html" = "/rust-2018/path-changes.html"
"/rust-2018/module-system/raw-identifiers.html" = "/rust-2018/path-changes.html"
"/rust-2018/module-system/path-clarity.html" = "/rust-2018/path-changes.html"
"/rust-2018/module-system/more-visibility-modifiers.html" = "/rust-2018/path-changes.html"
"/rust-2018/module-system/nested-imports-with-use.html" = "/rust-2018/path-changes.html"
"/rust-2018/error-handling-and-panics/index.html" = "/rust-2018/index.html"
"/rust-2018/error-handling-and-panics/the-question-mark-operator-for-easier-error-handling.html" = "/rust-2018/index.html"
"/rust-2018/error-handling-and-panics/question-mark-in-main-and-tests.html" = "/rust-2018/index.html"
"/rust-2018/error-handling-and-panics/controlling-panics-with-std-panic.html" = "/rust-2018/index.html"
"/rust-2018/error-handling-and-panics/aborting-on-panic.html" = "/rust-2018/index.html"
"/rust-2018/control-flow/index.html" = "/rust-2018/index.html"
"/rust-2018/control-flow/loops-can-break-with-a-value.html" = "/rust-2018/index.html"
"/rust-2018/control-flow/async-await-for-easier-concurrency.html" = "/rust-2018/index.html"
"/rust-2018/trait-system/index.html" = "/rust-2018/index.html"
"/rust-2018/trait-system/impl-trait-for-returning-complex-types-with-ease.html" = "/rust-2018/index.html"
"/rust-2018/trait-system/dyn-trait-for-trait-objects.html" = "/rust-2018/index.html"
"/rust-2018/trait-system/more-container-types-support-trait-objects.html" = "/rust-2018/index.html"
"/rust-2018/trait-system/associated-constants.html" = "/rust-2018/index.html"
"/rust-2018/trait-system/no-anon-params.html" = "/rust-2018/index.html"
"/rust-2018/slice-patterns.html" = "/rust-2018/index.html"
"/rust-2018/ownership-and-lifetimes/index.html" = "/rust-2018/index.html"
"/rust-2018/ownership-and-lifetimes/non-lexical-lifetimes.html" = "/rust-2018/index.html"
"/rust-2018/ownership-and-lifetimes/default-match-bindings.html" = "/rust-2018/index.html"
"/rust-2018/ownership-and-lifetimes/the-anonymous-lifetime.html" = "/rust-2018/index.html"
"/rust-2018/ownership-and-lifetimes/lifetime-elision-in-impl.html" = "/rust-2018/index.html"
"/rust-2018/ownership-and-lifetimes/inference-in-structs.html" = "/rust-2018/index.html"
"/rust-2018/ownership-and-lifetimes/simpler-lifetimes-in-static-and-const.html" = "/rust-2018/index.html"
"/rust-2018/data-types/index.html" = "/rust-2018/index.html"
"/rust-2018/data-types/field-init-shorthand.html" = "/rust-2018/index.html"
"/rust-2018/data-types/inclusive-ranges.html" = "/rust-2018/index.html"
"/rust-2018/data-types/128-bit-integers.html" = "/rust-2018/index.html"
"/rust-2018/data-types/operator-equals-are-now-implementable.html" = "/rust-2018/index.html"
"/rust-2018/data-types/union-for-an-unsafe-form-of-enum.html" = "/rust-2018/index.html"
"/rust-2018/data-types/choosing-alignment-with-the-repr-attribute.html" = "/rust-2018/index.html"
"/rust-2018/simd-for-faster-computing.html" = "/rust-2018/index.html"
"/rust-2018/macros/index.html" = "/rust-2018/index.html"
"/rust-2018/macros/custom-derive.html" = "/rust-2018/index.html"
"/rust-2018/macros/macro-changes.html" = "/rust-2018/index.html"
"/rust-2018/macros/at-most-once.html" = "/rust-2018/index.html"
"/rust-2018/the-compiler/index.html" = "/rust-2018/index.html"
"/rust-2018/the-compiler/improved-error-messages.html" = "/rust-2018/index.html"
"/rust-2018/the-compiler/incremental-compilation-for-faster-compiles.html" = "/rust-2018/index.html"
"/rust-2018/the-compiler/an-attribute-for-deprecation.html" = "/rust-2018/index.html"
"/rust-2018/rustup-for-managing-rust-versions.html" = "/rust-2018/index.html"
"/rust-2018/cargo-and-crates-io/index.html" = "/rust-2018/cargo.html"
"/rust-2018/cargo-and-crates-io/cargo-check-for-faster-checking.html" = "/rust-2018/cargo.html"
"/rust-2018/cargo-and-crates-io/cargo-install-for-easy-installation-of-tools.html" = "/rust-2018/cargo.html"
"/rust-2018/cargo-and-crates-io/cargo-new-defaults-to-a-binary-project.html" = "/rust-2018/cargo.html"
"/rust-2018/cargo-and-crates-io/cargo-rustc-for-passing-arbitrary-flags-to-rustc.html" = "/rust-2018/cargo.html"
"/rust-2018/cargo-and-crates-io/cargo-workspaces-for-multi-package-projects.html" = "/rust-2018/cargo.html"
"/rust-2018/cargo-and-crates-io/multi-file-examples.html" = "/rust-2018/cargo.html"
"/rust-2018/cargo-and-crates-io/replacing-dependencies-with-patch.html" = "/rust-2018/cargo.html"
"/rust-2018/cargo-and-crates-io/cargo-can-use-a-local-registry-replacement.html" = "/rust-2018/cargo.html"
"/rust-2018/cargo-and-crates-io/crates-io-disallows-wildcard-dependencies.html" = "/rust-2018/cargo.html"
"/rust-2018/documentation/index.html" = "/rust-2018/index.html"
"/rust-2018/documentation/new-editions-of-the-book.html" = "/rust-2018/index.html"
"/rust-2018/documentation/the-rust-bookshelf.html" = "/rust-2018/index.html"
"/rust-2018/documentation/the-rustonomicon.html" = "/rust-2018/index.html"
"/rust-2018/documentation/std-os-has-documentation-for-all-platforms.html" = "/rust-2018/index.html"
"/rust-2018/rustdoc/index.html" = "/rust-2018/index.html"
"/rust-2018/rustdoc/documentation-tests-can-now-compile-fail.html" = "/rust-2018/index.html"
"/rust-2018/rustdoc/rustdoc-uses-commonmark.html" = "/rust-2018/index.html"
"/rust-2018/platform-and-target-support/index.html" = "/rust-2018/index.html"
"/rust-2018/platform-and-target-support/libcore-for-low-level-rust.html" = "/rust-2018/index.html"
"/rust-2018/platform-and-target-support/webassembly-support.html" = "/rust-2018/index.html"
"/rust-2018/platform-and-target-support/global-allocators.html" = "/rust-2018/index.html"
"/rust-2018/platform-and-target-support/msvc-toolchain-support.html" = "/rust-2018/index.html"
"/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html" = "/rust-2018/index.html"
"/rust-2018/platform-and-target-support/cdylib-crates-for-c-interoperability.html" = "/rust-2018/index.html"
